### ISSUE TITLE
review mireot imports

### ISSUE THREAD

**Issue by mobb** [DataONEorg/sem-prov-ontologies#6]
1. eg, we have ecosystem-wide photosynthesis from ENVO, but no organism photosynthesis (in a different tree).
2. ENVO has new classes

**Comment by mobb** [comment]
last fall, we had problems getting the PATO import to fully load in Protege, eg, that not all children of 'physical object quality' were visible. Today, I see 15 - is that what we expect?

**Comment by mobb** [comment]
Here is the original problem we had with pato imports. probably it;s something wrong on our end.
https://github.com/OBOFoundry/purl.obolibrary.org/issues/236

**Comment by Olson87** [comment]
In order to trouble shoot this I decided to work on the ECSO-dl.owl from the main branch not the aRctic one. Currently, it seems that I have no import errors for external ontologies. However I initially had to directly import the PATO_import.owl, UO_import.owl, and ENVO_import.owl files after loading the ECSO-dl.owl from the sem-prov-ontologies github folder. As for PATO specifically within ECSO there are 15 children of 'physical object quality" and within the PATO_import.owl file there are only 12.  On Bio portal (http://bioportal.bioontology.org/ontologies/PATO?p=classes&conceptid=root ) there are only 11 children of 'physical object quality with 'aplastic/hypoplastic' missing. I am not sure which is "correct" nor why there are more in ECSO than in the PATO import file itself.

**Comment by Olson87** [comment]
Ontology Imports in ECSO versus Import Files: 
PATO_import.owl class count  #1610  in ECSO-dl.owl #1641
ENVO_import.owl class count #1812 in ECSO-dl.owl # 1814 
UO_import.owl class count #141 in ECSO-dl.owl # 153 
Oboe.owl class count # 292 in ECSO-dl.owl # 326 (from indirect imports?) 
skos-owl1-dl count #4 in ECSO-dl.owl # 4

**Comment by mobb** [comment]
It looks like the display problems in protege were solved by setting the languate rendering preferences to this string: "en, !" per the protege wiki https://protegewiki.stanford.edu/wiki/Protege4NamingAndRendering

generated these new issues: #35, #36
